### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by jadbaz** [geniuscd/phpSlimy#1]
This gives a weird error when I try to run it: `Genius Exception: Charly 123`.
Please help!

**Comment by geniuscd** [comment]
mmm... maybe you should try to extend the base middleware Exception handler.
adding an abstract class is a must.

**Comment by jadbaz** [comment]
It's still not working.
Now it says `Exception: John Cena`.

**Comment by geniuscd** [comment]
Can you please create a new repo in order to replicate your case? I would be happy to merge a unit test afterwards. PM it.

**Comment by geniuscd** [comment]
The following is closed due to Chuck Norris' involvement .
